### ISSUE TITLE
This section of the README file needs rephrasing.

### ISSUE THREAD

**Issue by michaeltinsley** [smartia-tech/backend-dev-test#2]
[Lines 34-36.](https://github.com/smartia-tech/backend-dev-test/blame/10cae2d983cbaf9b9dbc0c2c488ed14790530f3e/README.md#L34-L36)

I am unsure what it is meant to say so haven't updated it myself.

**Comment by thestgman** [comment]
Fixed here: https://github.com/smartia-tech/backend-dev-test/commit/9c557ef86e2acee3d63c10aead50a1b429f65afd?diff=split

Dunno why it also picked workspace.xml (due to the entry in .gitignore) but not worried about that one.
